# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a0640bbd886b2d8e228c40187648bb6b80677d0edaf4c5f79399556d00a83c95043a0c33ec503452c5ee72878f693347bf8db414693065dad0b35f8cddb7d14

test:
  secret_key_base: 8aef733727e977ec5d52d37fbd9bd367fbb4867e806d7d0bcb77302701070a857fed0bdacd2931054965012afa63bfa35a384e03779f6eb7cc8d71abe60b5190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
